import json

from gym_trainer.domain.llm_plans import build_llm_weekly_plan
from gym_trainer.domain.plans import build_functional_hypertrophy_plan


def test_build_llm_weekly_plan_accepts_valid_json():
    fallback = build_functional_hypertrophy_plan("2026-06-29")

    plan = build_llm_weekly_plan(
        week_start="2026-06-29",
        profile={"training_days": 1},
        recent_feedback=[],
        fallback_plan=fallback,
        generate_text=lambda _: json.dumps(
            {
                "week_start": "2026-06-29",
                "training_days": 1,
                "sessions": [
                    {
                        "day": "Monday",
                        "name": "LLM Push",
                        "goal": "Train safely",
                        "warmup": "Warm up",
                        "exercises": ["Bench press 3x8 @ RPE 7"],
                        "rest_guidance": "Rest 2 minutes",
                        "pain_modifications": "Stay pain-free",
                        "optional_cardio": "",
                        "notes": "Generated by test",
                    }
                ],
                "notes": "LLM plan",
            }
        ),
    )

    assert plan["planner_source"] == "llm"
    assert plan["sessions"][0]["name"] == "LLM Push"


def test_build_llm_weekly_plan_falls_back_on_invalid_json():
    fallback = build_functional_hypertrophy_plan("2026-06-29")

    plan = build_llm_weekly_plan(
        week_start="2026-06-29",
        profile={},
        recent_feedback=[],
        fallback_plan=fallback,
        generate_text=lambda _: "not json",
    )

    assert plan["planner_source"] == "deterministic_fallback"
    assert plan["sessions"][0]["name"] == fallback["sessions"][0]["name"]
